<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Login</name>
   <tag></tag>
   <elementGuidId>31ba9d95-fac9-4af4-944a-c5e4be5ee6d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div/div[1]/div/div[2]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div/div[1]/div/div[2]/h5</value>
      <webElementGuid>941b58eb-bb8c-4380-83c0-4c4ac3f1d00f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
