<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field-Search</name>
   <tag></tag>
   <elementGuidId>60011cda-3c94-4940-bceb-bf445aa99d0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/aside/nav/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/aside/nav/div[2]/div/div/input</value>
      <webElementGuid>0ea6e68a-9635-490a-a5e4-ed2620b2d07b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
